### ISSUE TITLE
Won't upload songs with the same track number and name (or the file name?)

### ISSUE THREAD

**Issue by azumukupoe** [jamesbrindle/YTMusicUploader#2]
I don't know how this software detect duplicates but I'm almost certain that it's not uploading "duplicate" files with different hashes

**Comment by jamesbrindle** [comment]
Hi,

The filename _should_ be irrelevant...

It uses an xxHash of a file to determine if it's been uploaded according to your local DB. YouTube Music itself appears to use the ID3 tags of the file as far as I can tell _(maybe sound acoustic signature matching but I'm not sure on that)._

I don't suppose you can share me your problematic files and I'll happily take a look.

Kind regards,

Jamie

**Comment by azumukupoe** [comment]
I can't upload the files since I don't know a good file hosting but for example, it doesn't upload the German and English version of [Kraftwerk ‎– 3-D (Der Katalog)](https://www.discogs.com/Kraftwerk-3-D-Der-Katalog/master/1185775) completely. Could you suggest a file hosting service that would allow me to upload large files?

**Comment by jamesbrindle** [comment]
Hey,

You can just put the files here if you like:

https://1drv.ms/u/s!At6EvCXZJAN6zOhqFkvUvzXVC5tMww?e=FuEzMw

Regards,

Jamie

**Comment by azumukupoe** [comment]
Sorry for the late response but just uploaded it now.
Thank you.

**Comment by jamesbrindle** [comment]
Hey, I've made a change and hopefully this should be fixed in the latest version: [https://github.com/jamesbrindle/YTMusicUploader/releases](https://github.com/jamesbrindle/YTMusicUploader/releases).

Give it try whenever you can... You may have to refresh the update states in the database (which you can do from the 'cog' icon - Manage YT Music form) to force check the tracks immediately rather then waiting for its next round of uploads checking.

Cheers.

**Comment by azumukupoe** [comment]
Well, the update didn't fix the issue for me, unfortunately...

**Comment by jamesbrindle** [comment]
Hmm, damn! OK I'll keep trying. I would have thought it would have worked, as it has for me:

[![N|Solid](https://portfolio.jb-net.co.uk/shared/ytmusicuploader-i2.png)](https://github.com/jamesbrindle/YTMusicUploader)

You were sort of right about filenames... Well, it compares the track title, album name and artist name in the ID3 tags against what's uploaded to YT Music to detect matches and thus avoid uploading the same file again, however the album that you supplied with 2 different version, does distinctively have different album names; the German one has (German Version) in the album name.

There was a fuzzy logic check, whereby anything in brackets would be removed which performing the match, however I've removed that now?

I'll have another try anyway.

cheers,

Jamie

**Comment by yamada-dokaben-taro** [comment]
id2 and 7 won't upload
[db.sql.txt](https://github.com/jamesbrindle/YTMusicUploader/files/5519699/db.sql.txt)

**Comment by jamesbrindle** [comment]
Still unable to replicate...

**Comment by branches78** [comment]
Hey, I noticed that YouTube Music avoids uploading duplicated songs by comparing the ID3 tag regardless if the filename is exactly the same between both files, however, if I edit the ID3 to something different, it then uploads the song.

The thing is, YT Music Uploader doesn't do the same, it seems to compare only the filename so I've been unable to upload two different versions of the same song with the same filename but different ID3 tags.

What gives?

**Comment by tberman333** [comment]
I have this same problem.  I have a lot of live music in my collection, so a ton of duplicate song names.  It seems that most of the tracks with duplicate names do not get uploaded, but I can go back and upload them manually on music.youtube.com and they upload correctly from there.  I would be happy to help test any changes you make (as I have a good amount of music to test with).
