### ISSUE TITLE
Add 'retry' functionality on 500 error

### ISSUE THREAD

**Issue by jamesbrindle** [jamesbrindle/YTMusicUploader#6]

**Comment by jamesbrindle** [comment]
Done

**Comment by eturk1** [comment]
oops, I just posted about 500 then thought to look at closed issues.
my v1.4.7 still hangs on 500 & must be killed
